import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import $RefParser from '@apidevtools/json-schema-ref-parser';
import { compile, type JSONSchema } from 'json-schema-to-typescript';
import * as prettier from 'prettier';

type SchemaWithDefs = JSONSchema & { $defs: Record<string, JSONSchema> };

function requireDef(defs: Record<string, JSONSchema>, key: string): JSONSchema {
  const def = defs[key];
  if (!def) throw new Error(`missing $defs.${key}`);
  return def;
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '../../..');
const SCHEMA_DIR = path.join(REPO_ROOT, 'protocol', 'schema');
const WIDGETS_DIR = path.join(SCHEMA_DIR, 'widgets');
const OUT_DIR = path.join(REPO_ROOT, 'app', 'src', 'protocol', 'generated');
const DOCS_MESSAGES_FILE = path.join(REPO_ROOT, 'docs', 'protocol', 'messages.md');

const COMPILE_OPTS = {
  bannerComment: '',
  style: { semi: true, singleQuote: true },
  additionalProperties: true, // PRT-06: unknown fields in a known message must be tolerated, not rejected.
} as const;

function header(source: string): string {
  return (
    '/**\n' +
    ` * AUTO-GENERATED by \`npm run gen\` (tools/gen-types) from ${source}.\n` +
    ' * DO NOT EDIT BY HAND — see CLAUDE.md and SPEC.md PRO-02.\n' +
    ' */\n\n'
  );
}

function pascalCase(id: string): string {
  return id.charAt(0).toUpperCase() + id.slice(1);
}

/** Runs generated output through the repo's own Prettier config before writing, so `npm run gen`
 * always produces output already matching `npm run lint` — no separate format pass, and a stable
 * diff for the CI alignment check (gen:check, PRO-02/DOC-03). */
async function writeFormatted(filePath: string, content: string): Promise<void> {
  const config = (await prettier.resolveConfig(filePath)) ?? {};
  const formatted = await prettier.format(content, { ...config, filepath: filePath });
  await writeFile(filePath, formatted);
}

/** Flattens the app→device "no nested object/array in extra fields" guard to `true`: it is a runtime
 * validation rule enforced by Ajv against the original schema file, not something a structural TS type
 * needs to (or can cleanly) express. */
function stripFlatGuard(schema: JSONSchema): JSONSchema {
  const copy = { ...schema } as JSONSchema & { additionalProperties?: unknown };
  if (copy.additionalProperties && typeof copy.additionalProperties === 'object') {
    copy.additionalProperties = true;
  }
  return copy;
}

/**
 * json-schema-to-typescript (still draft-07-oriented) does not understand draft 2020-12 tuples
 * (`prefixItems` + `items: false`) — it silently produces `never[]` — and it prefers a schema's own
 * `title` over the `name` argument passed to `compile()`, which fights our naming scheme. Both schema
 * files must stay valid 2020-12 for Ajv (§3, PRO-01), so this rewrites an in-memory copy for the TS
 * generator only: draft-07-style `items`/`additionalItems` tuples, and no `title`.
 */
function prepareForTsCompile(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(prepareForTsCompile);
  if (!node || typeof node !== 'object') return node;
  const obj = node as Record<string, unknown>;

  if (Array.isArray(obj.prefixItems)) {
    const { prefixItems, items, title: _title, $id: _id, ...rest } = obj;
    const transformedRest: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(rest)) transformedRest[k] = prepareForTsCompile(v);
    const tupleItems = (prefixItems as unknown[]).map(prepareForTsCompile);
    const additionalItems =
      items === false ? false : items === undefined ? undefined : prepareForTsCompile(items);
    return {
      ...transformedRest,
      items: tupleItems,
      ...(additionalItems !== undefined ? { additionalItems } : {}),
    };
  }

  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (k === 'title' || k === '$id') continue;
    out[k] = prepareForTsCompile(v);
  }
  return out;
}

async function widgetKinds(): Promise<string[]> {
  const files = await readdir(WIDGETS_DIR);
  return files
    .filter((f) => f.endsWith('.schema.json') && f !== 'common.schema.json')
    .map((f) => f.replace('.schema.json', ''))
    .sort();
}

async function genWidgets(): Promise<string> {
  const kinds = await widgetKinds();
  const parts: string[] = [];
  const names: string[] = [];
  for (const kind of kinds) {
    const file = path.join(WIDGETS_DIR, `${kind}.schema.json`);
    const dereferenced = (await $RefParser.dereference(file)) as JSONSchema;
    const name = `${pascalCase(kind)}Widget`;
    const ts = await compile(prepareForTsCompile(dereferenced) as JSONSchema, name, COMPILE_OPTS);
    parts.push(ts.trim());
    names.push(name);
  }
  const union =
    ['export type WidgetDeclaration =', ...names.map((n) => `  | ${n}`)].join('\n') + ';\n';
  return parts.join('\n\n') + '\n\n' + union;
}

async function genDeviceToApp(): Promise<string> {
  const file = path.join(SCHEMA_DIR, 'device-to-app.schema.json');
  const root = (await $RefParser.dereference(file)) as SchemaWithDefs;
  const prep = (key: string): JSONSchema =>
    prepareForTsCompile(requireDef(root.$defs, key)) as JSONSchema;

  const hi = await compile(prep('hi'), 'DeviceHiMessage', COMPILE_OPTS);
  const u = await compile(prep('u'), 'UpdateMessage', COMPILE_OPTS);
  const x = await compile(prep('x'), 'RemoveMessage', COMPILE_OPTS);
  const d = await compile(prep('d'), 'DataMessage', COMPILE_OPTS);
  const e = await compile(prep('e'), 'EventMessage', COMPILE_OPTS);
  const ack = await compile(prep('ack'), 'AckMessage', COMPILE_OPTS);
  const pong = await compile(prep('pong'), 'PongMessage', COMPILE_OPTS);

  const union = [
    'export type DeviceToAppMessage =',
    '  | DeviceHiMessage',
    '  | WidgetDeclaration',
    '  | UpdateMessage',
    '  | RemoveMessage',
    '  | DataMessage',
    '  | EventMessage',
    '  | AckMessage',
    '  | PongMessage;',
    '',
  ].join('\n');

  return [
    `import type { WidgetDeclaration } from './widgets.js';`,
    hi.trim(),
    u.trim(),
    x.trim(),
    d.trim(),
    e.trim(),
    ack.trim(),
    pong.trim(),
    union,
  ].join('\n\n');
}

async function genAppToDevice(): Promise<string> {
  const file = path.join(SCHEMA_DIR, 'app-to-device.schema.json');
  const root = (await $RefParser.dereference(file)) as SchemaWithDefs;
  const prep = (key: string): JSONSchema =>
    prepareForTsCompile(stripFlatGuard(requireDef(root.$defs, key))) as JSONSchema;

  const hi = await compile(prep('hi'), 'AppHiMessage', COMPILE_OPTS);
  const c = await compile(prep('c'), 'ControlMessage', COMPILE_OPTS);
  const ping = await compile(prep('ping'), 'PingMessage', COMPILE_OPTS);

  const union = [
    'export type AppToDeviceMessage =',
    '  | AppHiMessage',
    '  | ControlMessage',
    '  | PingMessage;',
    '',
  ].join('\n');

  return [hi.trim(), c.trim(), ping.trim(), union].join('\n\n');
}

/** Regenerates the DOC-02 generated block of docs/protocol/messages.md from the schema. */
async function genMessagesDoc(): Promise<void> {
  const d2a = (await $RefParser.dereference(
    path.join(SCHEMA_DIR, 'device-to-app.schema.json'),
  )) as SchemaWithDefs;
  const a2d = (await $RefParser.dereference(
    path.join(SCHEMA_DIR, 'app-to-device.schema.json'),
  )) as SchemaWithDefs;

  const rows = (defs: Record<string, JSONSchema>, order: string[]): string =>
    order
      .map((key) => {
        const def = defs[key] as JSONSchema & {
          properties?: Record<string, unknown>;
          required?: string[];
        };
        const props = Object.keys(def.properties ?? {}).filter((p) => p !== 't');
        const required = new Set(def.required ?? []);
        const fmt = (p: string): string => (required.has(p) ? `**${p}**` : p);
        return `| \`${key}\` | ${props.map(fmt).join(', ') || '—'} |`;
      })
      .join('\n');

  const kinds = await widgetKinds();

  const generated = [
    '<!-- generated:start -->',
    '',
    '### Device → app',
    '',
    '| `t` | Fields (**bold** = required) |',
    '|---|---|',
    rows(d2a.$defs, ['hi', 'u', 'x', 'd', 'e', 'ack', 'pong']),
    '| `w` | see widget catalog below — one schema per `k` |',
    '',
    '### App → device',
    '',
    '| `t` | Fields (**bold** = required) |',
    '|---|---|',
    rows(a2d.$defs, ['hi', 'c', 'ping']),
    '',
    '### Widget catalog',
    '',
    'One schema per `k` in `/protocol/schema/widgets/`: ' +
      kinds.map((k) => `\`${k}\``).join(', ') +
      '.',
    '',
    '<!-- generated:end -->',
  ].join('\n');

  const existing = await readFile(DOCS_MESSAGES_FILE, 'utf8');
  const markerRe = /<!-- generated:start -->[\s\S]*?<!-- generated:end -->/;
  if (!markerRe.test(existing)) {
    throw new Error(
      `${DOCS_MESSAGES_FILE} is missing <!-- generated:start/end --> markers (DOC-02)`,
    );
  }
  await writeFormatted(DOCS_MESSAGES_FILE, existing.replace(markerRe, generated));
}

async function main(): Promise<void> {
  await mkdir(OUT_DIR, { recursive: true });

  const widgetsTs = await genWidgets();
  const deviceToAppTs = await genDeviceToApp();
  const appToDeviceTs = await genAppToDevice();

  await writeFormatted(
    path.join(OUT_DIR, 'widgets.ts'),
    header('protocol/schema/widgets/*.schema.json') + widgetsTs,
  );
  await writeFormatted(
    path.join(OUT_DIR, 'messages.ts'),
    header('protocol/schema/device-to-app.schema.json + app-to-device.schema.json') +
      deviceToAppTs +
      '\n' +
      appToDeviceTs,
  );
  await writeFormatted(
    path.join(OUT_DIR, 'index.ts'),
    header('protocol/schema/**') +
      `export * from './widgets.js';\nexport * from './messages.js';\n`,
  );

  await genMessagesDoc();

  console.log(
    'gen-types: wrote app/src/protocol/generated/{widgets,messages,index}.ts and docs/protocol/messages.md',
  );
}

main().catch((err: unknown) => {
  console.error(err);
  process.exitCode = 1;
});
