import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import $RefParser from '@apidevtools/json-schema-ref-parser';
import Ajv2020 from 'ajv/dist/2020.js';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { compile, type JSONSchema } from 'json-schema-to-typescript';
import * as prettier from 'prettier';

const require = createRequire(import.meta.url);

type SchemaWithDefs = JSONSchema & { $defs: Record<string, JSONSchema> };

function requireDef(defs: Record<string, JSONSchema>, key: string): JSONSchema {
  const def = defs[key];
  if (!def) throw new Error(`missing $defs.${key}`);
  return def;
}

// Loose shape for walking a dereferenced schema when building the docs tables below — the
// `JSONSchema` type from json-schema-to-typescript is tuned for TS codegen, not for reading
// `description`/`enum`/`items` back out, so this is a permissive view of the same object.
interface DocSchemaNode {
  type?: string | string[];
  enum?: unknown[];
  const?: unknown;
  items?: DocSchemaNode;
  description?: string;
  properties?: Record<string, DocSchemaNode>;
  required?: string[];
  [key: string]: unknown;
}

function describeType(schema: DocSchemaNode): string {
  if (schema.const !== undefined) return `\`${JSON.stringify(schema.const)}\``;
  if (schema.enum) return schema.enum.map((v) => `\`${JSON.stringify(v)}\``).join(' \\| ');
  if (Array.isArray(schema.type)) return schema.type.join(' \\| ');
  if (Array.isArray(schema.prefixItems)) {
    return `[${(schema.prefixItems as DocSchemaNode[]).map(describeType).join(', ')}]`;
  }
  if (schema.type === 'array') return `${describeType(schema.items ?? {})}[]`;
  const union = (schema.oneOf ?? schema.anyOf) as DocSchemaNode[] | undefined;
  if (union) return union.map(describeType).join(' \\| ');
  return (schema.type as string | undefined) ?? 'any';
}

/** A `| Field | Type | Required | Description |` table for one message/object schema, skipping
 * `t` (already shown in the section heading) and any field named in `skip`. */
function fieldTable(def: DocSchemaNode, skip: string[] = []): string {
  const required = new Set(def.required ?? []);
  const rows = Object.entries(def.properties ?? {})
    .filter(([name]) => name !== 't' && !skip.includes(name))
    .map(([name, schema]) => {
      const req = required.has(name) ? '**yes**' : 'no';
      const desc = schema.description ?? '';
      return `| \`${name}\` | ${describeType(schema)} | ${req} | ${desc} |`;
    });
  return ['| Field | Type | Required | Description |', '|---|---|---|---|', ...rows].join('\n');
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '../../..');
const SCHEMA_DIR = path.join(REPO_ROOT, 'protocol', 'schema');
const WIDGETS_DIR = path.join(SCHEMA_DIR, 'widgets');
const OUT_DIR = path.join(REPO_ROOT, 'app', 'src', 'protocol', 'generated');
const DOCS_MESSAGES_FILE = path.join(REPO_ROOT, 'docs', 'protocol', 'messages.md');

const COMPILE_OPTS = {
  bannerComment: '',
  style: { semi: true, singleQuote: true },
  additionalProperties: true, // PRT-06: unknown fields in a known message must be tolerated, not rejected.
} as const;

function header(source: string): string {
  return (
    '/**\n' +
    ` * AUTO-GENERATED by \`npm run gen\` (tools/gen-types) from ${source}.\n` +
    ' * DO NOT EDIT BY HAND — see CLAUDE.md and SPEC.md PRO-02.\n' +
    ' */\n\n'
  );
}

function pascalCase(id: string): string {
  return id.charAt(0).toUpperCase() + id.slice(1);
}

/** Runs generated output through the repo's own Prettier config before writing, so `npm run gen`
 * always produces output already matching `npm run lint` — no separate format pass, and a stable
 * diff for the CI alignment check (gen:check, PRO-02/DOC-03). */
async function writeFormatted(filePath: string, content: string): Promise<void> {
  const config = (await prettier.resolveConfig(filePath)) ?? {};
  const formatted = await prettier.format(content, { ...config, filepath: filePath });
  await writeFile(filePath, formatted);
}

/** Flattens the app→device "no nested object/array in extra fields" guard to `true`: it is a runtime
 * validation rule enforced by Ajv against the original schema file, not something a structural TS type
 * needs to (or can cleanly) express. */
function stripFlatGuard(schema: JSONSchema): JSONSchema {
  const copy = { ...schema } as JSONSchema & { additionalProperties?: unknown };
  if (copy.additionalProperties && typeof copy.additionalProperties === 'object') {
    copy.additionalProperties = true;
  }
  return copy;
}

/**
 * json-schema-to-typescript (still draft-07-oriented) does not understand draft 2020-12 tuples
 * (`prefixItems` + `items: false`) — it silently produces `never[]` — and it prefers a schema's own
 * `title` keyword over the `name` argument passed to `compile()`, which fights our naming scheme.
 * Both schema files must stay valid 2020-12 for Ajv (§3, PRO-01), so this rewrites an in-memory
 * copy for the TS generator only: draft-07-style `items`/`additionalItems` tuples, and no `title`
 * *keyword* — a `properties.title` field (the widget's actual title string) is a data field, not
 * this keyword, and must survive.
 */
function prepareForTsCompile(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(prepareForTsCompile);
  if (!node || typeof node !== 'object') return node;
  const obj = node as Record<string, unknown>;

  if (Array.isArray(obj.prefixItems)) {
    const { prefixItems, items, title: _title, $id: _id, ...rest } = obj;
    const transformedRest: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(rest)) transformedRest[k] = prepareForTsCompile(v);
    const tupleItems = (prefixItems as unknown[]).map(prepareForTsCompile);
    const additionalItems =
      items === false ? false : items === undefined ? undefined : prepareForTsCompile(items);
    return {
      ...transformedRest,
      items: tupleItems,
      ...(additionalItems !== undefined ? { additionalItems } : {}),
    };
  }

  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    if (k === 'title' || k === '$id') continue; // schema-metadata title/$id — safe to drop here
    if (k === 'properties' && v && typeof v === 'object') {
      // Keys of a `properties` map are DATA FIELD NAMES, not schema keywords — a field
      // legitimately named "title" (the widget's display title, common.schema.json) must not be
      // stripped just because the string matches. Recurse into each field's own schema instead.
      const properties: Record<string, unknown> = {};
      for (const [fieldName, fieldSchema] of Object.entries(v as Record<string, unknown>)) {
        properties[fieldName] = prepareForTsCompile(fieldSchema);
      }
      out[k] = properties;
      continue;
    }
    out[k] = prepareForTsCompile(v);
  }
  return out;
}

async function widgetKinds(): Promise<string[]> {
  const files = await readdir(WIDGETS_DIR);
  return files
    .filter((f) => f.endsWith('.schema.json') && f !== 'common.schema.json')
    .map((f) => f.replace('.schema.json', ''))
    .sort();
}

async function genWidgets(): Promise<string> {
  const kinds = await widgetKinds();
  const parts: string[] = [];
  const names: string[] = [];
  for (const kind of kinds) {
    const file = path.join(WIDGETS_DIR, `${kind}.schema.json`);
    const dereferenced = (await $RefParser.dereference(file)) as JSONSchema;
    const name = `${pascalCase(kind)}Widget`;
    const ts = await compile(prepareForTsCompile(dereferenced) as JSONSchema, name, COMPILE_OPTS);
    parts.push(ts.trim());
    names.push(name);
  }
  const union =
    ['export type WidgetDeclaration =', ...names.map((n) => `  | ${n}`)].join('\n') + ';\n';
  return parts.join('\n\n') + '\n\n' + union;
}

async function genDeviceToApp(): Promise<string> {
  const file = path.join(SCHEMA_DIR, 'device-to-app.schema.json');
  const root = (await $RefParser.dereference(file)) as SchemaWithDefs;
  const prep = (key: string): JSONSchema =>
    prepareForTsCompile(requireDef(root.$defs, key)) as JSONSchema;

  const hi = await compile(prep('hi'), 'DeviceHiMessage', COMPILE_OPTS);
  const u = await compile(prep('u'), 'UpdateMessage', COMPILE_OPTS);
  const x = await compile(prep('x'), 'RemoveMessage', COMPILE_OPTS);
  const d = await compile(prep('d'), 'DataMessage', COMPILE_OPTS);
  const e = await compile(prep('e'), 'EventMessage', COMPILE_OPTS);
  const ack = await compile(prep('ack'), 'AckMessage', COMPILE_OPTS);
  const pong = await compile(prep('pong'), 'PongMessage', COMPILE_OPTS);

  const union = [
    'export type DeviceToAppMessage =',
    '  | DeviceHiMessage',
    '  | WidgetDeclaration',
    '  | UpdateMessage',
    '  | RemoveMessage',
    '  | DataMessage',
    '  | EventMessage',
    '  | AckMessage',
    '  | PongMessage;',
    '',
  ].join('\n');

  return [
    `import type { WidgetDeclaration } from './widgets.js';`,
    hi.trim(),
    u.trim(),
    x.trim(),
    d.trim(),
    e.trim(),
    ack.trim(),
    pong.trim(),
    union,
  ].join('\n\n');
}

async function genAppToDevice(): Promise<string> {
  const file = path.join(SCHEMA_DIR, 'app-to-device.schema.json');
  const root = (await $RefParser.dereference(file)) as SchemaWithDefs;
  const prep = (key: string): JSONSchema =>
    prepareForTsCompile(stripFlatGuard(requireDef(root.$defs, key))) as JSONSchema;

  const hi = await compile(prep('hi'), 'AppHiMessage', COMPILE_OPTS);
  const c = await compile(prep('c'), 'ControlMessage', COMPILE_OPTS);
  const ping = await compile(prep('ping'), 'PingMessage', COMPILE_OPTS);

  const union = [
    'export type AppToDeviceMessage =',
    '  | AppHiMessage',
    '  | ControlMessage',
    '  | PingMessage;',
    '',
  ].join('\n');

  return [hi.trim(), c.trim(), ping.trim(), union].join('\n\n');
}

const SCHEMA_IDS = {
  deviceToApp: 'https://schema.serialdash.dev/v1/device-to-app.schema.json',
  appToDevice: 'https://schema.serialdash.dev/v1/app-to-device.schema.json',
} as const;

/**
 * Pre-compiles the Ajv validators at build time (PRO-01: "Ajv, schemi compilati in build") rather
 * than shipping the schema + Ajv's compiler to run `new Function()`-based codegen in the browser
 * — that needs `unsafe-eval`, which the app's CSP (APP-NFR-05) deliberately does not grant.
 *
 * Ajv's ESM standalone output still emits a `require(...)` call for a couple of small runtime
 * helpers (e.g. `ucs2length`, used by `maxLength`/`minLength`) even with `code.esm: true` — a
 * known Ajv limitation. Turning those into `import` statements looks like the obvious fix, but
 * isn't a safe one: these helper modules use the Babel/TypeScript `exports.default = fn` +
 * `__esModule` convention, and reasonable-looking `import fn from '...'` fails at runtime with
 * "fn is not a function" under both Node's native CJS interop and Vite's dependency
 * pre-bundler — both wrap the whole CJS `exports` object as the default rather than unwrapping
 * it, differently from each other, so no single import form is safe across environments (found by
 * actually connecting to the simulator in a real browser, not just by `tsc`/`vitest` passing).
 *
 * The robust fix: since these helpers are tiny, pure, dependency-free functions, use Node's own
 * `require()` here — which, unlike a browser/bundler import, always interops correctly — to load
 * the real function, then inline its source directly into the generated file. No import, no
 * interop ambiguity, and it stays in sync with whatever `ajv` version generated the code.
 */
async function genValidators(): Promise<string> {
  const ajv = new Ajv2020({
    code: { source: true, esm: true },
    allErrors: true,
    allowUnionTypes: true,
  });

  for (const kind of await widgetKinds()) {
    ajv.addSchema(
      JSON.parse(await readFile(path.join(WIDGETS_DIR, `${kind}.schema.json`), 'utf8')),
    );
  }
  ajv.addSchema(JSON.parse(await readFile(path.join(WIDGETS_DIR, 'common.schema.json'), 'utf8')));
  ajv.addSchema(
    JSON.parse(await readFile(path.join(SCHEMA_DIR, 'device-to-app.schema.json'), 'utf8')),
  );
  ajv.addSchema(
    JSON.parse(await readFile(path.join(SCHEMA_DIR, 'app-to-device.schema.json'), 'utf8')),
  );

  let code = standaloneCode(ajv, {
    validateDeviceToApp: SCHEMA_IDS.deviceToApp,
    validateAppToDevice: SCHEMA_IDS.appToDevice,
  });

  const requirePattern = /const (\w+) = require\("([^"]+)"\)\.default;/g;
  code = code.replace(requirePattern, (_match, varName: string, importPath: string) => {
    const mod = require(importPath) as { default?: unknown };
    const fn = mod.default;
    if (typeof fn !== 'function') {
      throw new Error(`expected ${importPath}'s default export to be a function, got ${typeof fn}`);
    }
    return `const ${varName} = ${fn.toString()};`;
  });

  return code;
}

function genValidatorsTypes(): string {
  return [
    `import type { ValidateFunction } from 'ajv';`,
    `import type { DeviceToAppMessage, AppToDeviceMessage } from './messages.js';`,
    '',
    'export declare const validateDeviceToApp: ValidateFunction<DeviceToAppMessage>;',
    'export declare const validateAppToDevice: ValidateFunction<AppToDeviceMessage>;',
    '',
  ].join('\n');
}

// Short heading titles per message type — the schema's own per-field descriptions carry the real
// explanation; these just label the section so the table of contents / page skim reads cleanly.
const D2A_TITLES: Record<string, string> = {
  hi: 'Device presentation',
  u: 'Partial update',
  x: 'Remove widget',
  d: 'Data',
  e: 'Event',
  ack: 'Control acknowledgement',
  pong: 'Keep-alive reply',
};
const A2D_TITLES: Record<string, string> = {
  hi: 'Handshake request',
  c: 'Control command',
  ping: 'Keep-alive',
};

/** One `#### \`key\` — title` section: the def's own description, then its field table. */
function messageSection(
  key: string,
  titles: Record<string, string>,
  def: DocSchemaNode,
  skip: string[] = [],
): string {
  return [
    `#### \`${key}\` — ${titles[key] ?? key}`,
    '',
    def.description ?? '',
    '',
    fieldTable(def, skip),
  ].join('\n');
}

/** Regenerates the generated block of docs/protocol/messages.md from the schema. */
async function genMessagesDoc(): Promise<void> {
  const d2a = (await $RefParser.dereference(
    path.join(SCHEMA_DIR, 'device-to-app.schema.json'),
  )) as SchemaWithDefs as unknown as { $defs: Record<string, DocSchemaNode> };
  const a2d = (await $RefParser.dereference(
    path.join(SCHEMA_DIR, 'app-to-device.schema.json'),
  )) as SchemaWithDefs as unknown as { $defs: Record<string, DocSchemaNode> };
  const common = (await $RefParser.dereference(
    path.join(WIDGETS_DIR, 'common.schema.json'),
  )) as unknown as { $defs: Record<string, DocSchemaNode> };

  const kinds = await widgetKinds();

  const generated = [
    '<!-- generated:start -->',
    '',
    '### Device → app',
    '',
    'Every line the device sends is one of these, identified by its `t` field.',
    '',
    ...['hi', 'u', 'x', 'd', 'e', 'ack', 'pong'].map((key) =>
      messageSection(key, D2A_TITLES, d2a.$defs[key]!),
    ),
    '',
    '#### `w` — Widget declaration',
    '',
    `${d2a.$defs.w!.description ?? ''} See the widget catalog below for the full per-kind property list, and [common widget properties](#common-widget-properties) for the fields every kind shares.`,
    '',
    '### App → device',
    '',
    'Every line the app sends is one of these.',
    '',
    ...['hi', 'c', 'ping'].map((key) => messageSection(key, A2D_TITLES, a2d.$defs[key]!)),
    '',
    '### Common widget properties',
    '',
    'Every widget declared with `w` accepts these, regardless of kind (`t` and `k` aren\'t listed — `t` is always `"w"`, and `k` is the kind selector itself, covered in the widget catalog below).',
    '',
    fieldTable(common.$defs.widgetBase!, ['t', 'k']),
    '',
    '### Widget catalog',
    '',
    'One schema per `k` in `/protocol/schema/widgets/`: ' +
      kinds.map((k) => `\`${k}\``).join(', ') +
      '.',
    '',
    '<!-- generated:end -->',
  ].join('\n');

  const existing = await readFile(DOCS_MESSAGES_FILE, 'utf8');
  const markerRe = /<!-- generated:start -->[\s\S]*?<!-- generated:end -->/;
  if (!markerRe.test(existing)) {
    throw new Error(
      `${DOCS_MESSAGES_FILE} is missing <!-- generated:start/end --> markers (DOC-02)`,
    );
  }
  await writeFormatted(DOCS_MESSAGES_FILE, existing.replace(markerRe, generated));
}

async function main(): Promise<void> {
  await mkdir(OUT_DIR, { recursive: true });

  const widgetsTs = await genWidgets();
  const deviceToAppTs = await genDeviceToApp();
  const appToDeviceTs = await genAppToDevice();
  const validatorsJs = await genValidators();

  await writeFormatted(
    path.join(OUT_DIR, 'widgets.ts'),
    header('protocol/schema/widgets/*.schema.json') + widgetsTs,
  );
  await writeFormatted(
    path.join(OUT_DIR, 'messages.ts'),
    header('protocol/schema/device-to-app.schema.json + app-to-device.schema.json') +
      deviceToAppTs +
      '\n' +
      appToDeviceTs,
  );
  await writeFormatted(path.join(OUT_DIR, 'validators.js'), validatorsJs);
  await writeFormatted(
    path.join(OUT_DIR, 'validators.d.ts'),
    header('protocol/schema/** (Ajv standalone, PRO-01)') + genValidatorsTypes(),
  );

  await writeFormatted(
    path.join(OUT_DIR, 'index.ts'),
    header('protocol/schema/**') +
      `export * from './widgets.js';\nexport * from './messages.js';\nexport * from './validators.js';\n`,
  );

  await genMessagesDoc();

  console.log(
    'gen-types: wrote app/src/protocol/generated/{widgets,messages,validators,index}.* and docs/protocol/messages.md',
  );
}

main().catch((err: unknown) => {
  console.error(err);
  process.exitCode = 1;
});
